package telas;

import classes.Cliente;
import classes.Comanda;
import classes.Controle;
import classes.Entregador;
import classes.Funcionario;
import classes.Garcom;
import classes.Gerente;
import classes.ManipulaArquivos;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 * Classe para a tela de fechar a comanda
 */
public class FecharComanda extends javax.swing.JFrame {

    /** Atributo para a comanda que será finalizada */
    private Comanda comanda;
    
    /**
     * Creates new form FecharComanda
     */
    
    /**
     * Método construtor da classe
     * @param comanda Comanda que será finalizada
     */
    public FecharComanda(Comanda comanda) {
        initComponents();
        this.comanda = comanda;
        this.comanda.calculaValorParcial();
        this.lblValorDescricao.setText("R$ " + String.format("%.2f", this.comanda.getValorTotal()));

        double desconto;
        try {
            desconto = this.comanda.aplicarDesconto();
        } catch (Exception e) {
            desconto = 0;
        }
        this.lblDescontoDescricao.setText("- R$ " + String.format("%.2f", desconto));
        
        this.comanda.calculaValorParcial();
        if (this.comanda.getMesa() != null) { 
            // para quando o pedido for no salão
            this.comanda.setValorTotal(comanda.getValorTotal()*1.1);
            this.lblAdicional.setText("Valor com 10%:");
            this.lblAdicionalDescricao.setText("R$ " + String.format("%.2f", this.comanda.getValorTotal()));
            
        } else { // para quando o pedido for delivery
            this.comanda.setValorTotal(this.comanda.getValorTotal()+13.90);
            this.lblAdicional.setText("Valor com frete:");
            this.lblAdicionalDescricao.setText("R$ " + String.format("%.2f", this.comanda.getValorTotal()));
        }
        this.comanda.setValorTotal(this.comanda.getValorTotal()-desconto);
        this.lblValorFinalDescricao.setText("R$ " + String.format("%.2f", this.comanda.getValorTotal()));
        
        if (this.comanda.getCliente() != null)
            this.lblClienteDescricao.setText(this.comanda.getCliente().getCPF());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFinalizando = new javax.swing.JLabel();
        pnlDadosPedido = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        lblDesconto = new javax.swing.JLabel();
        lblValorFinal = new javax.swing.JLabel();
        lblValorDescricao = new javax.swing.JLabel();
        lblDescontoDescricao = new javax.swing.JLabel();
        lblValorFinalDescricao = new javax.swing.JLabel();
        btnFinalizarPedido = new javax.swing.JButton();
        lblLinhaSeparatoria = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblClienteDescricao = new javax.swing.JLabel();
        lblAdicional = new javax.swing.JLabel();
        lblAdicionalDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalização do pedido");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/Comanda.png")).getImage());

        lblFinalizando.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFinalizando.setText("Finalizando Pedido");

        pnlDadosPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValor.setText("Valor:");

        lblDesconto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDesconto.setText("Desconto:");

        lblValorFinal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValorFinal.setText("Valor final:");

        lblValorDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValorDescricao.setText("R$ XXX,XX");

        lblDescontoDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDescontoDescricao.setText("- R$ XX,XX");

        lblValorFinalDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblValorFinalDescricao.setText("R$ XXX,XX");

        btnFinalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnFinalizarPedido.setText("Finalizar pedido");
        btnFinalizarPedido.setToolTipText("Fecha o pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        lblLinhaSeparatoria.setText("-------------------------------------------------------------------------------------------------------------");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCliente.setText("Cliente:");

        lblClienteDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblClienteDescricao.setText("Não identificado");

        lblAdicional.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdicional.setText("Valor com 10%:");

        lblAdicionalDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAdicionalDescricao.setText("R$ XXX,XX");

        javax.swing.GroupLayout pnlDadosPedidoLayout = new javax.swing.GroupLayout(pnlDadosPedido);
        pnlDadosPedido.setLayout(pnlDadosPedidoLayout);
        pnlDadosPedidoLayout.setHorizontalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLinhaSeparatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnFinalizarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblValorFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorFinalDescricao)
                .addGap(140, 140, 140))
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCliente)
                    .addComponent(lblDesconto)
                    .addComponent(lblValor)
                    .addComponent(lblAdicional))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblValorDescricao)
                        .addComponent(lblClienteDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAdicionalDescricao))
                    .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                        .addComponent(lblDescontoDescricao)
                        .addGap(46, 46, 46)))
                .addGap(93, 93, 93))
        );
        pnlDadosPedidoLayout.setVerticalGroup(
            pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPedidoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblClienteDescricao))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(lblValorDescricao))
                .addGap(19, 19, 19)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdicional)
                    .addComponent(lblAdicionalDescricao))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesconto)
                    .addComponent(lblDescontoDescricao))
                .addGap(29, 29, 29)
                .addComponent(lblLinhaSeparatoria)
                .addGap(18, 18, 18)
                .addGroup(pnlDadosPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorFinal)
                    .addComponent(lblValorFinalDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnFinalizarPedido)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(pnlDadosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblFinalizando)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblFinalizando)
                .addGap(34, 34, 34)
                .addComponent(pnlDadosPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        // faz todas as operações para fechar a comanda
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Pedido finalizado com sucesso.", "Finalizado", JOptionPane.INFORMATION_MESSAGE);
        double valorComanda = this.comanda.getValorTotal();
        this.comanda.fecharComanda();
        
        // ALTERANDO O ARQUIVO DE INFORMAÇÕES GERAIS
        String dadosGerais;
        Object[] dadosArquivo = ManipulaArquivos.importandoDadosGerais();
        ManipulaArquivos.apagarTxt("Gerais.txt");
        double receita = Double.parseDouble(dadosArquivo[0].toString()) + valorComanda; // calcula a receita total com a nova comanda e escreve no arquivo
        int quantPedidos = Integer.parseInt(dadosArquivo[1].toString())+1;
        dadosGerais = (receita+", "+ quantPedidos);
        ManipulaArquivos.escreverTxt("Gerais.txt", dadosGerais);
        
        // ALTERANDO OS ARQUIVOS DE CLIENTES E FUNCIONÁRIOS
        ManipulaArquivos.apagarTxt("Clientes.txt");
        for (Cliente c : Controle.clientes) {
            String dadosCliente;
            dadosCliente = (c.getNome()+", "+ c.getCPF()+", "+ c.getEmail()+", "+c.getTelefone()+", "+c.getEndereço()+", "+ c.getAniversario().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))+ ", "+ c.getQuantidadePedidos()+"\n");
            ManipulaArquivos.escreverTxt("Clientes.txt", dadosCliente);
        }
        
        ManipulaArquivos.apagarTxt("Funcionarios.txt");
        for (Funcionario f : Controle.funcionarios) {
            String dadosFuncionario;
            if (f instanceof Gerente)
                dadosFuncionario = ("Gerente, " + f.getNome()+", "+ f.getCPF()+", "+ f.getSalario()+", "+ f.getDiaContratado().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))+ ", "+((Gerente)f).getSenha()+"\n");
            else if (f instanceof Garcom)
                dadosFuncionario = ("Garcom, " + f.getNome()+", "+ f.getCPF()+", "+ f.getSalario()+", "+f.getDiaContratado().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))+", " + ((Garcom)f).getQuantidadeAtendimentos()+ "\n");
            else
                dadosFuncionario = ("Entregador, " + f.getNome()+", "+ f.getCPF()+", "+ f.getSalario()+", "+f.getDiaContratado().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))+", "+((Entregador)f).getCNH()+", " + ((Entregador)f).getQuantidadeEntregas()+ "\n");
            ManipulaArquivos.escreverTxt("Funcionarios.txt", dadosFuncionario);
        }
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FecharComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FecharComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FecharComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FecharComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FecharComanda().setVisible(true); NÃO É UTILIZADO
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JLabel lblAdicional;
    private javax.swing.JLabel lblAdicionalDescricao;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblClienteDescricao;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblDescontoDescricao;
    private javax.swing.JLabel lblFinalizando;
    private javax.swing.JLabel lblLinhaSeparatoria;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorDescricao;
    private javax.swing.JLabel lblValorFinal;
    private javax.swing.JLabel lblValorFinalDescricao;
    private javax.swing.JPanel pnlDadosPedido;
    // End of variables declaration//GEN-END:variables
}
