package telas;

import classes.Controle;
import classes.Funcionario;
import classes.ManipulaArquivos;
import classes.Produto;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Classe para a tela de relatório geral
 */
public class RelatorioGeral extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioFinanceiro
     */
    
    /**
     * Método construtor da classe
     */
    public RelatorioGeral() {
        initComponents();
        // preenche os dados do dia atual e gerais nos respectivos campos
        this.lblDataDiaDescricao.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        this.lblReceitaDiaDescricao.setText("R$ " + String.format("%.2f", Controle.getReceitaDia()));
        this.lblQuantidadePedidosDiaDescricao.setText(String.valueOf(Controle.getQuantidadePedidosDia()) + " pedidos");
        
        Produto maisVendido = Produto.procuraPratoMaisVendido();
    
        this.lblPratoMaisVendidoDiaDescricao.setText(maisVendido.getNome() + ": " + maisVendido.getQuantPedido());
        
        // recebe os dados do arquivo Gerais.txt
        Object[] dados_gerais = ManipulaArquivos.importandoDadosGerais(); 
        
        this.lblReceitaTotalDescricao.setText("R$ " + String.format("%.2f", dados_gerais[0]));
        double soma = 0;
        for (Funcionario func : Controle.funcionarios)
            soma += func.getSalario();
        this.lblDespesaSalarioDescricao.setText("- R$ " + String.format("%.2f", soma));
        this.lblQuantidadeFuncionariosDescricao.setText(Controle.funcionarios.size() + " funcionários");
        this.lblQuantidadeClientesDescricao.setText(Controle.clientes.size() + " clientes");
        this.lblQuantidadePedidosTotalDescricao.setText(dados_gerais[1].toString() + " pedidos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDiaAtual = new javax.swing.JPanel();
        lblReceitaDia = new javax.swing.JLabel();
        lblQuantidadePedidosDia = new javax.swing.JLabel();
        lblDataDia = new javax.swing.JLabel();
        lblPratoMaisVendidoDia = new javax.swing.JLabel();
        lblDataDiaDescricao = new javax.swing.JLabel();
        lblReceitaDiaDescricao = new javax.swing.JLabel();
        lblQuantidadePedidosDiaDescricao = new javax.swing.JLabel();
        lblPratoMaisVendidoDiaDescricao = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlGeral = new javax.swing.JPanel();
        lblReceitaTotal = new javax.swing.JLabel();
        lblDespesaSalario = new javax.swing.JLabel();
        lblQuantidadeFuncionarios = new javax.swing.JLabel();
        lblQuantidadeClientes = new javax.swing.JLabel();
        lblQuantidadePedidosTotal = new javax.swing.JLabel();
        lblReceitaTotalDescricao = new javax.swing.JLabel();
        lblDespesaSalarioDescricao = new javax.swing.JLabel();
        lblQuantidadeFuncionariosDescricao = new javax.swing.JLabel();
        lblQuantidadeClientesDescricao = new javax.swing.JLabel();
        lblQuantidadePedidosTotalDescricao = new javax.swing.JLabel();
        lblRelatórioGeral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Financeiro");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio1.png")).getImage());

        pnlDiaAtual.setBorder(javax.swing.BorderFactory.createTitledBorder("Dia atual"));

        lblReceitaDia.setText("Receita: ");

        lblQuantidadePedidosDia.setText("Quantidade de pedidos:");

        lblDataDia.setText("Data:");

        lblPratoMaisVendidoDia.setText("Prato mais vendido do dia:");

        lblDataDiaDescricao.setText("dd/MM/yyyy");

        lblReceitaDiaDescricao.setText("R$ XXXX");

        lblQuantidadePedidosDiaDescricao.setText("XX pedidos");

        lblPratoMaisVendidoDiaDescricao.setText("Prato: XX");

        javax.swing.GroupLayout pnlDiaAtualLayout = new javax.swing.GroupLayout(pnlDiaAtual);
        pnlDiaAtual.setLayout(pnlDiaAtualLayout);
        pnlDiaAtualLayout.setHorizontalGroup(
            pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiaAtualLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReceitaDia)
                    .addComponent(lblDataDia)
                    .addComponent(lblQuantidadePedidosDia)
                    .addComponent(lblPratoMaisVendidoDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDataDiaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblReceitaDiaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuantidadePedidosDiaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPratoMaisVendidoDiaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(237, 237, 237))
        );
        pnlDiaAtualLayout.setVerticalGroup(
            pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDiaAtualLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDia)
                    .addComponent(lblDataDiaDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceitaDia)
                    .addComponent(lblReceitaDiaDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadePedidosDia)
                    .addComponent(lblQuantidadePedidosDiaDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDiaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPratoMaisVendidoDia)
                    .addComponent(lblPratoMaisVendidoDiaDescricao))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643764-back-backward-left-reply-turn_113415 (1).png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        pnlGeral.setBorder(javax.swing.BorderFactory.createTitledBorder("GERAL"));

        lblReceitaTotal.setText("Receita total:");

        lblDespesaSalario.setText("Despesa mensal de salário:");

        lblQuantidadeFuncionarios.setText("Quantidade de funcionários:");

        lblQuantidadeClientes.setText("Quantidade de clientes cadastrados:");

        lblQuantidadePedidosTotal.setText("Quantidade de pedidos:");

        lblReceitaTotalDescricao.setText("R$ XXXX");

        lblDespesaSalarioDescricao.setText("- R$ XXXX");

        lblQuantidadeFuncionariosDescricao.setText("XX funcionários");

        lblQuantidadeClientesDescricao.setText("XX clientes");

        lblQuantidadePedidosTotalDescricao.setText("XX pedidos");

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReceitaTotal)
                    .addComponent(lblDespesaSalario)
                    .addComponent(lblQuantidadeFuncionarios)
                    .addComponent(lblQuantidadeClientes)
                    .addComponent(lblQuantidadePedidosTotal))
                .addGap(43, 43, 43)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReceitaTotalDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDespesaSalarioDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuantidadeFuncionariosDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(lblQuantidadeClientesDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuantidadePedidosTotalDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(214, 214, 214))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceitaTotal)
                    .addComponent(lblReceitaTotalDescricao))
                .addGap(18, 18, 18)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDespesaSalarioDescricao)
                    .addComponent(lblDespesaSalario))
                .addGap(18, 18, 18)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidadeFuncionariosDescricao)
                    .addComponent(lblQuantidadeFuncionarios))
                .addGap(18, 18, 18)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidadeClientesDescricao)
                    .addComponent(lblQuantidadeClientes))
                .addGap(18, 18, 18)
                .addGroup(pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidadePedidosTotalDescricao)
                    .addComponent(lblQuantidadePedidosTotal))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblRelatórioGeral.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRelatórioGeral.setText("Relatório Geral");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(180, 180, 180)
                .addComponent(lblRelatórioGeral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDiaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltar)
                    .addComponent(lblRelatórioGeral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDiaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // fecha a tela de relatório
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioGeral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioGeral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblDataDia;
    private javax.swing.JLabel lblDataDiaDescricao;
    private javax.swing.JLabel lblDespesaSalario;
    private javax.swing.JLabel lblDespesaSalarioDescricao;
    private javax.swing.JLabel lblPratoMaisVendidoDia;
    private javax.swing.JLabel lblPratoMaisVendidoDiaDescricao;
    private javax.swing.JLabel lblQuantidadeClientes;
    private javax.swing.JLabel lblQuantidadeClientesDescricao;
    private javax.swing.JLabel lblQuantidadeFuncionarios;
    private javax.swing.JLabel lblQuantidadeFuncionariosDescricao;
    private javax.swing.JLabel lblQuantidadePedidosDia;
    private javax.swing.JLabel lblQuantidadePedidosDiaDescricao;
    private javax.swing.JLabel lblQuantidadePedidosTotal;
    private javax.swing.JLabel lblQuantidadePedidosTotalDescricao;
    private javax.swing.JLabel lblReceitaDia;
    private javax.swing.JLabel lblReceitaDiaDescricao;
    private javax.swing.JLabel lblReceitaTotal;
    private javax.swing.JLabel lblReceitaTotalDescricao;
    private javax.swing.JLabel lblRelatórioGeral;
    private javax.swing.JPanel pnlDiaAtual;
    private javax.swing.JPanel pnlGeral;
    // End of variables declaration//GEN-END:variables
}
