package telas;

import classes.Comanda;
import classes.Controle;
import classes.PedidosTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * Classe para a tela de relatório de pedidos
 */
public class RelatorioPedidos extends javax.swing.JFrame {
    
    /** Atributo para armazenar um PedidoTableModel */
    private PedidosTableModel modelo;
    
    /**
     * Creates new form RelatorioPedidos
     */
    
    /**
     * Método construtor da classe
     */
    public RelatorioPedidos() {
        initComponents();
        this.modelo = new PedidosTableModel();
        this.tblRelatorioPedidos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblPesquisar = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnImagemPesquisar = new javax.swing.JButton();
        pnlRelatorioPedidos = new javax.swing.JPanel();
        scrRelatorioPedidos = new javax.swing.JScrollPane();
        tblRelatorioPedidos = new javax.swing.JTable();
        btnCancelarPedido = new javax.swing.JButton();
        btnEditarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Pedidos");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio1.png")).getImage());

        btnVoltar.setBackground(new java.awt.Color(242, 242, 242));
        btnVoltar.setForeground(new java.awt.Color(242, 242, 242));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643764-back-backward-left-reply-turn_113415 (1).png"))); // NOI18N
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPesquisar.setText("Pesquisar:");

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisar.setToolTipText("Pesquise pelo ID da comanda");
        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
        });

        btnImagemPesquisar.setBackground(new java.awt.Color(242, 242, 242));
        btnImagemPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier-1_icon-icons.com_56924 (1).png"))); // NOI18N
        btnImagemPesquisar.setToolTipText("Pesquisar");
        btnImagemPesquisar.setBorder(null);
        btnImagemPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagemPesquisarActionPerformed(evt);
            }
        });

        scrRelatorioPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        tblRelatorioPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Hora do pedido", "Valor total", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRelatorioPedidos.getTableHeader().setReorderingAllowed(false);
        scrRelatorioPedidos.setViewportView(tblRelatorioPedidos);
        if (tblRelatorioPedidos.getColumnModel().getColumnCount() > 0) {
            tblRelatorioPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblRelatorioPedidos.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblRelatorioPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblRelatorioPedidos.getColumnModel().getColumn(2).setResizable(false);
            tblRelatorioPedidos.getColumnModel().getColumn(3).setResizable(false);
            tblRelatorioPedidos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnCancelarPedido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnEditarPedido.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEditarPedido.setText("Editar pedido");
        btnEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRelatorioPedidosLayout = new javax.swing.GroupLayout(pnlRelatorioPedidos);
        pnlRelatorioPedidos.setLayout(pnlRelatorioPedidosLayout);
        pnlRelatorioPedidosLayout.setHorizontalGroup(
            pnlRelatorioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRelatorioPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarPedido)
                .addGap(166, 166, 166)
                .addComponent(btnEditarPedido)
                .addGap(292, 292, 292))
        );
        pnlRelatorioPedidosLayout.setVerticalGroup(
            pnlRelatorioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrRelatorioPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRelatorioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPedido)
                    .addComponent(btnEditarPedido))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(lblPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnImagemPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRelatorioPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisar)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagemPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addComponent(pnlRelatorioPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // fecha a tela de relatório
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnImagemPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagemPesquisarActionPerformed
        // quando clicado, faz a pesquisa do ID digitado
        boolean achou = false;
        for (int i=0; i<modelo.getRowCount(); i++) {
            if (String.valueOf(this.modelo.getValueAt(i, 0)).equals(this.txtPesquisar.getText().trim())) {
                achou = true;
                this.tblRelatorioPedidos.setRowSelectionInterval(i, i);
            }
        }
        if (!achou)
            JOptionPane.showMessageDialog(null, "Não foi encontrado um pedido com o ID digitado.", "Atenção", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnImagemPesquisarActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // cancela o pedido selecionado
        try {
            Comanda pedido = this.modelo.getComanda(this.tblRelatorioPedidos.getSelectedRow());
            int ind = Controle.comandas.indexOf(pedido);
            if (!pedido.isFinalizada()) {
                this.modelo.remove(ind);
                if (!pedido.isDelivery()) {
                    // para quando o pedido for no salão
                    pedido.getMesa().liberarMesa();
                    pedido.getMesa().colorirBotao();
                }    
                JOptionPane.showMessageDialog(null, "Pedido cancelado com sucesso.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Um pedido já finalizado não pode ser cancelado.", "Atenção", JOptionPane.WARNING_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um pedido para cancelar.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPedidoActionPerformed
        // abre a tela de editar pedido, de acordo com o pedido selecionado
        try {
            Comanda pedido = this.modelo.getComanda(this.tblRelatorioPedidos.getSelectedRow());
            if (!pedido.isFinalizada()) {
                this.setVisible(false);
                new EditarPedido(pedido, this).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Um pedido já finalizado não pode ser editado.", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um pedido para editar.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarPedidoActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        // pesquisar pela tecla Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            // quando clicado, faz a pesquisa do ID digitado
            boolean achou = false;
            for (int i=0; i<modelo.getRowCount(); i++) {
                if (String.valueOf(this.modelo.getValueAt(i, 0)).equals(this.txtPesquisar.getText().trim())) {
                    achou = true;
                    this.tblRelatorioPedidos.setRowSelectionInterval(i, i);
                }
            }
            if (!achou)
                JOptionPane.showMessageDialog(null, "Não foi encontrado um pedido com o ID digitado.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtPesquisarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnEditarPedido;
    private javax.swing.JButton btnImagemPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JPanel pnlRelatorioPedidos;
    private javax.swing.JScrollPane scrRelatorioPedidos;
    private javax.swing.JTable tblRelatorioPedidos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
